// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNvMkYyUsjvzkf2G2Uioncdan5q39jpN0',
    appId: '1:195583721287:web:a38d94266b255c4948d662',
    messagingSenderId: '195583721287',
    projectId: 'flash-chat-34af3',
    authDomain: 'flash-chat-34af3.firebaseapp.com',
    storageBucket: 'flash-chat-34af3.appspot.com',
    measurementId: 'G-CJYM2RS1EZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOLwoiA95bBoxC0pfyQd9RM4ifgwiSwTg',
    appId: '1:195583721287:android:c05d598df066479548d662',
    messagingSenderId: '195583721287',
    projectId: 'flash-chat-34af3',
    storageBucket: 'flash-chat-34af3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABcthMVtItv7rM6ZEMf3uH7r96i-7PSZE',
    appId: '1:195583721287:ios:c3065022660fdd2848d662',
    messagingSenderId: '195583721287',
    projectId: 'flash-chat-34af3',
    storageBucket: 'flash-chat-34af3.appspot.com',
    iosClientId: '195583721287-4fk47n9ipf8k1q7fjj536opkjuol4r09.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABcthMVtItv7rM6ZEMf3uH7r96i-7PSZE',
    appId: '1:195583721287:ios:c3065022660fdd2848d662',
    messagingSenderId: '195583721287',
    projectId: 'flash-chat-34af3',
    storageBucket: 'flash-chat-34af3.appspot.com',
    iosClientId: '195583721287-4fk47n9ipf8k1q7fjj536opkjuol4r09.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChat',
  );
}
